"""Add currency field to houses

Revision ID: 05d14d919317
Revises: 66e2b985d0f1
Create Date: 2025-01-25 17:12:47.922189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d14d919317'
down_revision: Union[str, None] = '66e2b985d0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'currency')
    # ### end Alembic commands ###
