"""Added completed to booking and full to house

Revision ID: 099965cb4c51
Revises: fbef1d79dd1c
Create Date: 2025-03-28 18:40:10.439629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099965cb4c51'
down_revision: Union[str, None] = 'fbef1d79dd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
