"""Added social media links and email and phone number field to houses

Revision ID: 3740d7d991f0
Revises: 05d14d919317
Create Date: 2025-01-25 21:04:22.577323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3740d7d991f0'
down_revision: Union[str, None] = '05d14d919317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('email', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('whatsapp', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('facebook', sa.String(), nullable=True))
    op.alter_column('houses', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'Kenya'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'country',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Kenya'::text"))
    op.drop_column('houses', 'facebook')
    op.drop_column('houses', 'whatsapp')
    op.drop_column('houses', 'linkedin')
    op.drop_column('houses', 'phone_number')
    op.drop_column('houses', 'email')
    # ### end Alembic commands ###
