"""transaction table changed

Revision ID: 7db732f10bbc
Revises: 2733252c0eb3
Create Date: 2025-03-10 11:30:40.383223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db732f10bbc'
down_revision: Union[str, None] = '2733252c0eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=False))
    op.alter_column('transactions', 'house_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'house_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'description')
    # ### end Alembic commands ###
