"""Added deposit to house table

Revision ID: 8988b437117c
Revises: 121afa461da6
Create Date: 2025-03-13 16:20:08.191689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8988b437117c'
down_revision: Union[str, None] = '121afa461da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('deposit', sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'deposit')
    # ### end Alembic commands ###
