"""Added added_at column on Cart table

Revision ID: 9db05a07faa5
Revises: cee684ab541d
Create Date: 2024-12-13 18:34:36.338599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db05a07faa5'
down_revision: Union[str, None] = 'cee684ab541d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'added_at')
    # ### end Alembic commands ###
