"""Added some fields on Bookings table

Revision ID: c14c0d99556e
Revises: d1773cc6d55a
Create Date: 2025-01-17 00:35:46.406299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14c0d99556e'
down_revision: Union[str, None] = 'd1773cc6d55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'start_date')
    # ### end Alembic commands ###
