"""created transaction table and added some more fields on house and user tables

Revision ID: c739eec18404
Revises: b1831f581eb6
Create Date: 2025-01-13 20:38:34.898651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c739eec18404"
down_revision: Union[str, None] = "b1831f581eb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the 'HouseStatus' enum first
    house_status_enum = sa.Enum("on_sale", "sold", "booked", name="housestatus")
    house_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("mpesa", "stripe", "paypal", "bank_transfer", "other", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["house_id"], ["houses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(op.f("ix_transactions_transaction_id"), "transactions", ["transaction_id"], unique=True)
    op.add_column("bookings", sa.Column("booking_date", sa.DateTime(), nullable=True))
    op.add_column("bookings", sa.Column("room_count", sa.Integer(), nullable=False))
    op.alter_column(
        "bookings",
        "house_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "bookings",
        "user_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_column("bookings", "start_date")
    op.drop_column("bookings", "created_at")
    op.drop_column("bookings", "status")
    op.drop_column("bookings", "end_date")
    op.drop_column("bookings", "rooms_no")
    op.drop_column("bookings", "updated_at")
    op.add_column("houses", sa.Column("booked_rooms", sa.Integer(), nullable=True))
    op.add_column("houses", sa.Column("remaining_rooms", sa.Integer(), nullable=True))
    op.add_column(
        "houses",
        sa.Column("status", sa.Enum("on_sale", "sold", "booked", name="housestatus"), nullable=True),
    )
    op.add_column("houses", sa.Column("on_sale", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("houses", "on_sale")
    op.drop_column("houses", "status")
    op.drop_column("houses", "remaining_rooms")
    op.drop_column("houses", "booked_rooms")
    op.add_column(
        "bookings",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bookings",
        sa.Column("rooms_no", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "bookings",
        sa.Column("end_date", sa.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "bookings",
        sa.Column("status", sa.Enum("PENDING", "APPROVED", "CANCELED", name="bookingstatus"), autoincrement=False, nullable=False),
    )
    op.add_column(
        "bookings",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bookings",
        sa.Column("start_date", sa.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "bookings",
        "user_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "bookings",
        "house_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_column("bookings", "room_count")
    op.drop_column("bookings", "booking_date")
    op.drop_index(op.f("ix_transactions_transaction_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")

    # Drop the 'HouseStatus' enum last
    house_status_enum = sa.Enum("on_sale", "sold", "booked", name="housestatus")
    house_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

   
