"""Status on booking table

Revision ID: c8e1e3ecab0d
Revises: c14c0d99556e
Create Date: 2025-01-17 00:44:20.731664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e1e3ecab0d'
down_revision: Union[str, None] = 'c14c0d99556e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='verificationstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
