"""Added some fields on Bookings table and added start date

Revision ID: d1773cc6d55a
Revises: 3df301cfd0f0
Create Date: 2025-01-16 22:58:18.809116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1773cc6d55a'
down_revision: Union[str, None] = '3df301cfd0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
