"""Added room_no column in booking table

Revision ID: f2059376080d
Revises: 3a3688a2ed22
Create Date: 2024-12-11 16:41:44.796425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2059376080d'
down_revision: Union[str, None] = '3a3688a2ed22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rooms_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'rooms_no')
    # ### end Alembic commands ###
